CREATE DATABASE IF NOT EXISTS calculator;
USE calculator;

CREATE TABLE IF NOT EXISTS evaluations (
  id INT AUTO_INCREMENT PRIMARY KEY,
  value1 DOUBLE NOT NULL,
  value2 DOUBLE NOT NULL,
  operation ENUM('+','-','*','/') NOT NULL,
  answer DOUBLE NOT NULL,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);
